### ISSUE TITLE
Can it be compatible to the next version from itsnbites?

### ISSUE THREAD

**Issue by cyberpunkbln** [parasyte/sonant-rs#15]
Hello,
is it possible to expand it to the expanded sonant version under [https://sb.bitsnbites.eu/](https://sb.bitsnbites.eu/) ?
thx

**Comment by parasyte** [comment]
According to their help documentation, the synthesizer used is [SoundBox](https://gitlab.com/mbitsnbites/soundbox) which is entirely unrelated to sonant. At minimum it would require a different song parser, and at most a different synth. It isn't clear whether any code can be shared between these at all.

**Comment by cyberpunkbln** [comment]
ah okay thx

**Comment by parasyte** [comment]
FWIW, that synth does have a function to import sonant files. So, it seems that it might be a superset of sonant: https://gitlab.com/mbitsnbites/soundbox/-/blob/3a339d6384106c7676afc5ea3cdeca46e1964047/gui.js#L1189
